version: '3.8'

services:
  backend:
    build: ./backend
    container_name: feedback-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./feedback.db
    volumes:
      - ./backend/feedback.db:/app/feedback.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: feedback-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000

networks:
  default:
    name: feedback-network 