services:
  # Backend API service
  - type: web
    name: feedback-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      alembic upgrade head
      python seed.py
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./feedback.db
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # Frontend service
  - type: web
    name: feedback-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://feedback-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 